version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - flask_app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
